// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA74PbZ1k-7Z4Hbfn2iYwgc3oh-uhPKVdM',
    appId: '1:686344377592:web:600167b1b746e44ee3570d',
    messagingSenderId: '686344377592',
    projectId: 'syriaapp-d1fa0',
    authDomain: 'syriaapp-d1fa0.firebaseapp.com',
    storageBucket: 'syriaapp-d1fa0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODbjpor6KB3qaUUm63AifUOkOFsgl_EM',
    appId: '1:686344377592:android:c26e2b4b9e8796a2e3570d',
    messagingSenderId: '686344377592',
    projectId: 'syriaapp-d1fa0',
    storageBucket: 'syriaapp-d1fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcgyEFijfUyzmKBfWjSgVR4axPhI_tBKM',
    appId: '1:686344377592:ios:1d39521f9a037939e3570d',
    messagingSenderId: '686344377592',
    projectId: 'syriaapp-d1fa0',
    storageBucket: 'syriaapp-d1fa0.firebasestorage.app',
    iosBundleId: 'com.example.syriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcgyEFijfUyzmKBfWjSgVR4axPhI_tBKM',
    appId: '1:686344377592:ios:1d39521f9a037939e3570d',
    messagingSenderId: '686344377592',
    projectId: 'syriaapp-d1fa0',
    storageBucket: 'syriaapp-d1fa0.firebasestorage.app',
    iosBundleId: 'com.example.syriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA74PbZ1k-7Z4Hbfn2iYwgc3oh-uhPKVdM',
    appId: '1:686344377592:web:f1d0c6bf293da620e3570d',
    messagingSenderId: '686344377592',
    projectId: 'syriaapp-d1fa0',
    authDomain: 'syriaapp-d1fa0.firebaseapp.com',
    storageBucket: 'syriaapp-d1fa0.firebasestorage.app',
  );
}
